version: 1
formatters:
  simple:
    format: "%(asctime)s [%(levelname)-5.5s] %(message)s"
    datefmt: "%Y%m%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  consoleJ:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    mode: "a"
loggers:
  __main__:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  jupyter:
    level: DEBUG
    handlers: [consoleJ]
    propagate: no
  root:
    level: DEBUG
    handlers: [console, file]
